<?php

return [
    'stickers'    => [
        '1' => "✊",
        '2' => "✌",
        '3' => "✋",
    ],

    'reklama'     => PHP_EOL . "➖➖➖➖➖➖➖➖➖" . PHP_EOL . "<a href='https://t.me/Nakrutka_insta_tg_uz/17'>O'z narxida Telegram Premium💳</a>",
    // The Telegram BOT api token
    'token'       => env('TELEGRAM_TOKEN'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode'   => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations
    'config'      => [
        'polling' => ['timeout' => 30],
    ],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes'      => true,

    // Enable or disable Nutgram mixins
    'mixins'      => false,

    // Path to save files generated by nutgram:make command
    'namespace'   => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
];
